name: zmall
description: Zmall E-commerce App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.2.0+331

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  heroicons_flutter: ^0.4.0
  http: ^1.5.0
  # http: ^1.4.0
  shimmer:
  flutter_spinkit:
  # shared_preferences:
  shared_preferences: ^2.5.3
  url_launcher: ^6.0.3
  # mobile_scanner:
  # qr_code_scanner:
  modal_progress_hud_nsn: ^0.5.1
  geolocator: ^14.0.2
  fl_location: ^5.0.0
  cached_network_image: ^3.2.0
  flutter_map:
  uuid: ^4.4.0
  smooth_star_rating_null_safety: ^1.0.4+2
  rate_my_app: ^2.0.0
  google_maps_flutter: ^2.6.1
  intl: ^0.20.2
  path_provider:
  image_picker:
  overlay_support: ^2.1.0
  # firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  # firebase_analytics: ^11.4.3
  firebase_analytics: ^12.0.0
  firebase_messaging: ^16.0.0
  firebase_in_app_messaging: ^0.9.0
  #
  photo_view: ^0.15.0
  flutter_inappwebview: ^6.1.5
  timezone:
  font_awesome_flutter:
  country_code_picker: ^3.0.0
  percent_indicator: ^4.0.0
  provider:
  # rive:
  flutter_datetime_picker: ^1.5.1
  # flutter_svg:
  # crypto: ^3.0.3
  encrypt: ^5.0.3
  package_info_plus: ^8.0.0
  flutter_staggered_grid_view:

  #
  sms_autofill:
  # flutter_animate:

module:
  androidX: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
  uses-material-design: true

  assets:
    - images/
    - images/pl_logos/
    - images/store_tags/
#    - packages/timezone/data/2021a.tzf

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages

# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
